name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # 如果你的預設分支是 master，請改成 master

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4

      - name: Install and Build 🔧
        run: |
          npm ci
          npm run build

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist # Vite 打包後的資料夾名稱
          branch: gh-pages # 部署到的分支名稱
